In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error


In [10]:
# coloumns that are important for model
#amount
#location
#title
# carpet area
# furshing
#bathroom


In [ ]:
# coloumn that are important
newdf=df[['location','Carpet Area','Transaction','Bathroom','Amount(in rupees)','Ownership','Furnishing','Balcony']]

In [4]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   location           187531 non-null  object
 1   Carpet Area        106858 non-null  object
 2   Transaction        187448 non-null  object
 3   Bathroom           186703 non-null  object
 4   Amount(in rupees)  187531 non-null  object
 5   Ownership          122014 non-null  object
 6   Furnishing         184634 non-null  object
 7   Balcony            138596 non-null  object
dtypes: object(8)
memory usage: 11.4+ MB


In [21]:
newdf['Carpet Area'] = newdf['Carpet Area'].astype(str).str.extract(r'(\d+)').astype(float)

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\3385072934.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Carpet Area'] = newdf['Carpet Area'].astype(str).str.extract(r'(\d+)').astype(float)


In [22]:
newdf['Carpet Area'].unique()[:20]

array([ 500.,  473.,  779.,  530.,  635.,   nan,  550.,  900.,  950.,
       1820.,  675.,  647.,  600.,  430.,  665.,  557.,  870.,  288.,
        925.,  434.])

In [23]:
newdf['Balcony'] = newdf['Balcony'].replace({'>10': '11', '> 10': '11'})

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\3614143422.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Balcony'] = newdf['Balcony'].replace({'>10': '11', '> 10': '11'})


In [7]:
newdf['Balcony'].unique()

array(['2', nan, '1', '3', '4', '11', '6', '5', '7', '10', '8', '9'],
      dtype=object)

In [8]:
newdf['Bathroom'] = newdf['Bathroom'].replace({'>10': '11', '> 10': '11'})

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\285762806.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Bathroom'] = newdf['Bathroom'].replace({'>10': '11', '> 10': '11'})


In [9]:
newdf['Bathroom'] = newdf['Bathroom'].astype(float)



C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\493143086.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Bathroom'] = newdf['Bathroom'].astype(float)


In [10]:
newdf['Balcony'] = newdf['Balcony'].astype(float)

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\126376824.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Balcony'] = newdf['Balcony'].astype(float)


In [11]:
newdf['Bathroom'].unique()

array([ 1.,  2.,  3.,  4.,  6., nan,  5., 10.,  9.,  8., 11.,  7.])

In [12]:
df["Amount(in rupees)"].unique()[:20]

array(['42 Lac ', '98 Lac ', '1.40 Cr ', '25 Lac ', '1.60 Cr ', '45 Lac ',
       '16.5 Lac ', '60 Lac ', '1.36 Cr ', '1.35 Cr ', '4.25 Cr ',
       '75 Lac ', '90 Lac ', '37 Lac ', '35 Lac ', '54 Lac ', '1.65 Cr ',
       '85 Lac ', '1.28 Cr ', 'Call for Price'], dtype=object)

In [13]:
import numpy as np
import re

def convert_amount(x):
    x = str(x).lower().strip()

    # Handle unknown price
    if "call" in x:
        return np.nan

    # extract number
    nums = re.findall(r"[\d.]+", x)
    if not nums:
        return np.nan
    
    num = float(nums[0])

    if "lac" in x or "lakh" in x:
        return num * 1e5
    elif "cr" in x or "crore" in x:
        return num * 1e7

    return num


In [14]:
newdf["Amount(in rupees)"] = newdf["Amount(in rupees)"].apply(convert_amount)

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\1480751808.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf["Amount(in rupees)"] = newdf["Amount(in rupees)"].apply(convert_amount)


In [15]:
newdf["Amount(in rupees)"].unique()[:20]

array([ 4200000.,  9800000., 14000000.,  2500000., 16000000.,  4500000.,
        1650000.,  6000000., 13600000., 13500000., 42500000.,  7500000.,
        9000000.,  3700000.,  3500000.,  5400000., 16500000.,  8500000.,
       12800000.,       nan])

In [16]:
newdf["Amount(in rupees)"] = newdf["Amount(in rupees)"].astype(float)

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\175616507.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf["Amount(in rupees)"] = newdf["Amount(in rupees)"].astype(float)


In [39]:
#newdf["Amount(in rupees)"] = newdf["Amount(in rupees)"].fillna(df["Amount(in rupees)"].median())

In [18]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   location           187531 non-null  object 
 1   Carpet Area        106858 non-null  object 
 2   Transaction        187448 non-null  object 
 3   Bathroom           186703 non-null  float64
 4   Amount(in rupees)  177847 non-null  float64
 5   Ownership          122014 non-null  object 
 6   Furnishing         184634 non-null  object 
 7   Balcony            138596 non-null  float64
dtypes: float64(3), object(5)
memory usage: 11.4+ MB


FILLING NAN VALUES


In [24]:

newdf['Carpet Area'] = newdf['Carpet Area'].fillna(newdf['Carpet Area'].median())
newdf['Transaction'] = newdf['Transaction'].fillna("rent/lease")
newdf['Bathroom'] = newdf['Bathroom'].fillna(newdf['Bathroom'].median())
newdf['Ownership'] = newdf['Ownership'].fillna("Freehold")
newdf['Furnishing'] = newdf['Furnishing'].fillna("Unfurnished")
newdf['Balcony'] = newdf['Balcony'].fillna(2)


C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\2177040220.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Carpet Area'] = newdf['Carpet Area'].fillna(newdf['Carpet Area'].median())
C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\2177040220.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['Transaction'] = newdf['Transaction'].fillna("rent/lease")
C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\2177040220.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice f

In [25]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   location           187531 non-null  object 
 1   Carpet Area        187531 non-null  float64
 2   Transaction        187531 non-null  object 
 3   Bathroom           187531 non-null  float64
 4   Amount(in rupees)  177847 non-null  float64
 5   Ownership          187531 non-null  object 
 6   Furnishing         187531 non-null  object 
 7   Balcony            187531 non-null  float64
dtypes: float64(4), object(4)
memory usage: 11.4+ MB


In [26]:
newdf.dropna(inplace=True)

C:\Users\shrid\AppData\Local\Temp\ipykernel_7388\2211793558.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf.dropna(inplace=True)


In [27]:
newdf.isnull().sum()

location             0
Carpet Area          0
Transaction          0
Bathroom             0
Amount(in rupees)    0
Ownership            0
Furnishing           0
Balcony              0
dtype: int64

In [28]:
# creating featues or x
features = [
    'location','Carpet Area','Transaction','Bathroom','Amount(in rupees)','Ownership','Furnishing','Balcony']

In [29]:
# creating target or y
target= 'Amount(in rupees)'

In [30]:
X = newdf[features]
y = newdf[target]

In [31]:
# 5. IDENTIFY NUMERIC & CATEGORICAL COLUMNS
numerical_cols = ['Carpet Area', 'Bathroom', 'Balcony']
categorical_cols = ['location', 'Furnishing', 'Transaction', 'Ownership']

In [32]:
# 6. BUILD TRANSFORMERS
numeric_transformer = Pipeline([('scaler', StandardScaler())])
categorical_transformer = Pipeline([('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])


In [33]:
# 7. FINAL MODEL PIPELINE
model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=200, random_state=42))
])

In [34]:
# 8. TRAIN/TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
# 9. TRAIN MODEL
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Carpet Area', 'Bathroom',
                                                   'Balcony']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['location', 'Furnishing',
                                                   'Transaction',
                                                   'Ownership'])])),
                ('regressor',
                 RandomForestRegressor(n_estimators=200, random_state=42))])

In [38]:
y_pred

array([13715351.77009912,  3793591.23607321,  5051053.75911925, ...,
        6500000.        ,  3318742.88461538, 43499264.4269212 ])